# variables/languages.py
# Developer Team: MUSHAK
# Kharazmi 1404-1405

from PyQt5.QtGui import QFont


# دیکشنری اصلی زبان‌ها
languages = {
    'persian': {
        # A
        'about_button': 'درباره ما',
        'about_message': '''
                        نام برنامه: برنامه ساخت جلد
                        توسعه‌دهندگان: تیم موشک
                        نسخه: {}
                        پایه: هشتم
                        مدرسه: استعدادهای درخشان مشکینی
                        شماره تماس با ما: 09300828112 - 09941100534

                        ما با هدف تسهیل فرآیند طراحی جلدهای خلاقانه و حرفه‌ای
                        برنامه ساخت جلد را توسعه داده‌ایم
                        این برنامه به طور ویژه برای صنف دانشجویان و صحافین کتاب طراحی شده
                        تا بتوانند به سادگی جلدهایی منحصر به فرد خلق کنند

                        ما در گروه توسعه موشک با تمرکز بر تکمیل و فعال‌سازی تمامی قابلیت‌ها
                        تجربه‌ای بی‌نقص را برای شما فراهم خواهیم کرد

                        جشنواره خوارزمی 1404-1405
                        پشتیبانی: example@example.com
                        ''',
        'about_title': 'درباره برنامه',
        'about_tooltip': 'درباره برنامه و توسعه‌دهندگان',
        'ai_extract': 'استخراج با هوش مصنوعی',
        'ai_extract_failed': 'خطا در استخراج اطلاعات',
        'ai_extract_success': 'اطلاعات با موفقیت استخراج شد',
        'ai_extract_tooltip': 'استخراج خودکار عنوان، نویسنده و تاریخ از فایل PDF با هوش مصنوعی',
        'app_title': 'ساخت جلد',
        'app_up_to_date': 'برنامه بروز است',
        'apply': 'اعمال',
        'author': 'نام نویسنده',
        'author_font': 'فونت نام نویسنده',
        'author_name': 'نام نویسنده',
        'author_placeholder': 'نام نویسنده',
        'author_tooltip': 'نام نویسنده پایان‌نامه را وارد کنید',
        'auto_rotate': 'چرخش خودکار',
        'average': 'متوسط',
        'average_all': 'میانگین جلد در روز:',

        # B
        'back': 'بازگشت',
        'back_tooltip': 'بازگشت به صفحه قبل',
        'background_color': 'رنگ پس زمینه',
        'background_tooltip': 'انتخاب رنگ پس‌زمینه برنامه',
        'bad': 'ضعیف',
        'book_cover': 'ساخت جلد کتاب',
        'book_dimensions': 'ابعاد کتاب',
        'book_settings': 'تنظیمات کتاب',
        'book_title': 'عنوان کتاب',
        'both_sides_printed': 'پایان نامه دو رو چاپ شده',
        'both_sides_tooltip': 'اگر پایان‌نامه دو رو چاپ شده است تیک بزنید',

        # C
        'calendar_icon': '📅',
        'calendar_tooltip': 'انتخاب تاریخ از تقویم',
        'cancel': 'انصراف',
        'cancel_create': 'ساخت لغو شود؟',
        'changed': 'تغییر یافت',
        'check_again': 'بررسی مجدد',
        'check_update': 'بررسی به روزرسانی',
        'checking': 'در حال بررسی...',
        'checking_updates': 'در حال بررسی بروزرسانی...',
        'choose_back_page': 'صفحه پشت جلد را انتخاب کنید',
        'choose_front_page': 'صفحه روی جلد را انتخاب کنید',
        'clear_all': 'پاک کردن همه',
        'clear_all_confirm': 'آیا از پاک کردن کامل تاریخچه مطمئن هستید؟',
        'clear_all_success': 'تمام تاریخچه با موفقیت پاک شد',
        'clear_all_tooltip': 'پاک کردن تمام تاریخچه',
        'clear_remember_question': 'آیا می‌خواهید اطلاعات ورود (Remember Me) نیز پاک شود؟',
        'clear_search': 'پاک کردن جستجو',
        'close': 'بستن',
        'close_tooltip': 'بستن برنامه',
        'comment': 'نظر شما',
        'comment_placeholder': 'نظر خود را در مورد برنامه بنویسید...',
        'confirm_password': 'تکرار رمز عبور',
        'confirm_password_placeholder': 'رمز عبور را دوباره وارد کنید',
        'connecting_github': 'در حال ارتباط با گیت هاب...',
        'construction_info': 'اطلاعات ساخت',
        'copyed': 'کپی شد',
        'cover': 'جلد',
        'cover_created': 'جلد ساخته شد',
        'cover_created_success': 'جلد با موفقیت ساخته شد',
        'created_at': 'تاریخ ایجاد',
        'creation_date': 'تاریخ ایجاد',
        'current_version': 'نسخه فعلی',
        'current_version_checking': 'نسخه فعلی: در حال بررسی...',
        'current_version_unknown': 'نسخه فعلی: نامشخص',

        # D
        'date': 'تاریخ',
        'date_placeholder': 'تاریخ',
        'date_tooltip': 'تاریخ پایان‌نامه را وارد کنید',
        'delete': 'حذف',
        'delete_confirm': 'آیا از حذف {} مطمئن هستید؟',
        'description': 'توضیحات',
        'developer_team': 'تیم توسعه موشک',
        'dissertation_cover': 'ساخت جلد پایان نامه',
        'dissertation_number': 'پایان نامه چند صفحه دارد؟',
        'dissertation_tooltip': 'ساخت جلد پایان‌نامه',
        'download': 'دانلود',
        'download_error': 'خطا در دانلود',
        'downloading_updating': 'در حال دانلود و به روزرسانی...',
        'drag_drop_hint': 'فایل PDF را اینجا بکشید و رها کنید',

        # E
        'edit': 'ویرایش',
        'email': 'ایمیل',
        'email_placeholder': 'ایمیل خود را وارد کنید',
        'empty_credentials': 'لطفاً نام کاربری و رمز عبور را وارد کنید',
        'empty_fields_error': 'فیلدهای زیر خالی هستند:\n{}',
        'empty_history': 'تاریخچه خالی است',
        'enter_page_count': 'تعداد صفحات را وارد کنید',
        'enter_spine_first': 'لطفاً ابتدا مقدار عطف را وارد کنید',
        'enter_title_first': 'لطفاً ابتدا عنوان را وارد کنید',
        'enter_valid_number': 'لطفاً یک عدد معتبر وارد کنید',
        'err': 'لطفا در عطف و اندازه ها عدد وارد کنید',
        'error': 'خطا',
        'error_during_update': 'خطا در هنگام به روزرسانی:',
        'error_extract': 'خطا در استخراج فایل‌ها. نمی‌توان دایرکتوری اصلی مخزن را پیدا کرد.',
        'error_network_during_update': 'خطای شبکه در هنگام به روزرسانی:',
        'error_restarting_program': 'خطا در راه اندازی مجدد برنامه:',
        'error_starting': 'خطا در راه اندازی:',
        'excellent': 'عالی',
        'exit': 'خروج',
        'extracting': 'در حال استخراج...',

        # F
        'feedback_error': 'خطا در ارسال بازخورد',
        'feedback_thanks': 'از نظر شما متشکریم!',
        'feedback_title': 'نظر شما',
        'file_and_size': 'فایل و ابعاد',
        'file_name': 'نام فایل',
        'file_saved_to': 'فایل در مسیر زیر ذخیره شد',
        'file_section': 'فایل ها',
        'file_selected': 'فایل انتخاب شد',
        'filter_date_range': 'فیلتر بازه زمانی',
        'folder_selected': 'پوشه انتخاب شد',
        'font': 'فونت',
        'font_sample': 'نمونه متن',
        'form_cleared': 'فرم با موفقیت پاک شد',
        'full_name': 'نام کامل',
        'full_name_placeholder': 'نام و نام خانوادگی',

        # G
        'general': 'عمومی',
        'github_connection_error': 'خطا در ارتباط با گیت هاب',
        'github_error': 'خطا در ارتباط با گیت هاب',
        'gilded_book_cover': 'ساخت جلد کتاب های تذهیب دار',
        'good': 'خوب',
        'guest': 'مهمان',
        'guest_login': 'ورود به عنوان مهمان',
        'guest_login_error': 'خطا در ورود به عنوان مهمان',
        'guest_welcome': 'به عنوان مهمان خوش آمدید',
        'guide': 'راهنما',
        'guide_button': 'راهنما',
        'guide_result': 'نتیجه نهایی:\n• جلد نمایش داده می‌شود\n• فایل در مسیر انتخاب شده ذخیره می‌شود',
        'guide_step1_desc': 'عنوان (بخش عطف)، نام نویسنده، تاریخ و مقدار عطف را وارد کنید.',
        'guide_step1_title': 'مرحله ۱: اطلاعات پایه',
        'guide_step2_desc': 'فایل PDF پایان نامه را انتخاب کرده و مسیر ذخیره فایل نهایی را مشخص کنید.',
        'guide_step2_title': 'مرحله ۲: انتخاب فایل و محل ذخیره',
        'guide_step3_desc': 'روی دکمه شروع ساخت کلیک کنید. سپس صفحات روی جلد و پشت جلد را انتخاب کنید.',
        'guide_step3_title': 'مرحله ۳: ساخت و ذخیره جلد',
        'guide_tooltip': 'راهنمای استفاده از برنامه',

        # H
        'has_latin_page_off': 'بدون صفحه لاتین',
        'has_latin_page_on': 'دارای صفحه لاتین',
        'has_latin_page_text': 'پایان نامه صفحه لاتین دارد',
        'hello': 'سلام',
        'history_all_time': 'همیشه',
        'history_button': 'تاریخچه',
        'history_last_3_months': '۳ ماه گذشته',
        'history_last_6_months': '۶ ماه گذشته',
        'history_last_year': 'سال گذشته',
        'history_stats': 'آمار تاریخچه',
        'history_this_month': 'این ماه',
        'history_this_week': 'این هفته',
        'history_this_year': 'امسال',
        'history_today': 'امروز',
        'history_tooltip': 'مشاهده تاریخچه ساخت جلدها',

        # I
        'id': 'شناسه: {} \n {}',
        'inactive': 'غیرفعال',
        'inactive_frame': 'این بخش در به روزرسانی‌های بعد فعال خواهد شد',
        'info_title': 'اطلاعات پایان نامه',

        # K
        'Kharazmi': 'خوارزمی',
        'keyboard_shortcuts': 'میانبرهای صفحه کلید',

        # L
        'language': 'زبان',
        'language_tooltip': 'تغییر زبان برنامه',
        'latest_version': 'آخرین نسخه',
        'latest_version_checking': 'آخرین نسخه: در حال بررسی',
        'level': 'سطح',
        'level_tooltip': 'سطح پایان‌نامه را انتخاب کنید (برای پایان‌نامه‌های حوزوی)',
        'link': 'لینک',
        'loading': 'در حال بارگذاری...',
        'loading_database': 'در حال اتصال به پایگاه داده...',
        'loading_fonts': 'در حال بارگذاری فونت‌ها...',
        'loading_modules': 'در حال بارگذاری ماژول‌ها...',
        'loading_repos': 'در حال بارگذاری اطلاعات',
        'loading_theme': 'در حال راه‌اندازی تم...',
        'login': 'ورود',
        'logout': 'خروج از حساب',
        'logout_confirm': 'آیا از خروج از حساب کاربری مطمئن هستید؟',
        'logo_n_found': 'لوگو یافت نشد',

        # M
        'main_menu': 'منوی اصلی برنامه',
        'main_script_not_found': 'اسکریپت اصلی \'main.py\' یافت نشد. نمی‌توان برنامه را مجدداً راه اندازی کرد.',
        'media_access_denied': 'دسترسی به فایل ممکن نیست',
        'media_format_error': 'فرمت فایل پشتیبانی نمی‌شود',
        'media_network_error': 'خطا در شبکه',
        'media_resource_error': 'خطا در بارگذاری فایل',
        'media_service_missing': 'سرویس پخش در دسترس نیست',
        'media_unknown_error': 'خطای ناشناخته در پخش',
        'minimize': 'کوچک‌سازی پنجره',
        'months': ['فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر', 'دی', 'بهمن', 'اسفند'],
        'more_info': 'اطلاعات بیشتر',

        # N
        'new_version_available': 'نسخه جدید {} موجود است',
        'new_version_found': 'نسخه جدید',
        'no': 'خیر',
        'no_account': 'حساب کاربری ندارید؟',
        'no_back_cover': 'بدون صفحه پشت جلد',
        'no_back_cover_tooltip': 'اگر پایان‌نامه صفحه پشت جلد ندارد، این گزینه را انتخاب کنید',
        'no_description': 'بدون توضیحات',
        'no_file_selected': 'فایلی انتخاب نشده است',
        'no_folder_selected': 'پوشه ای انتخاب نشده است',
        'no_level': 'بدون سطح',
        'no_logo_selected': 'لوگو انتخاب نشده است',
        'no_other_programs': 'هیچ برنامه دیگری یافت نشد',
        'no_page_selected': 'هیچ صفحه‌ای انتخاب نشده است',
        'no_results': 'نتیجه‌ای یافت نشد',
        'notebook_cover': 'ساخت جلد دفتر مدارس',
        'number_all': 'تعداد کل جلدهای ساخته شده:',

        # O
        'open_file': 'باز کردن فایل',
        'open_location': 'باز کردن مسیر',
        'original_path': 'مسیر اصلی',
        'other_colors': 'رنگ‌های دیگر',
        'other_colors_tooltip': 'انتخاب رنگ دلخواه برای دکمه‌ها از Color Picker',
        'other_programs': 'برنامه های دیگر',
        'other_programs_title': 'سایر برنامه های ما',
        'other_tooltip': 'مشاهده برنامه‌های دیگر',
        'output_file_name': 'نام فایل خروجی',

        # P
        'page_number': 'صفحه',
        'pages_doubled': 'صفحات دو برابر می‌شود',
        'password': 'رمز عبور',
        'password_min_length': 'رمز عبور حداقل ۴ کاراکتر باید باشد',
        'password_mismatch': 'رمز عبور و تکرار آن مطابقت ندارند',
        'password_placeholder': 'رمز عبور خود را وارد کنید',
        'pause_rotation': 'توقف چرخش',
        'pdf_file': 'فایل PDF',
        'pdf_file_cannot_be_opened': 'فایل PDF قابل باز شدن نیست:',
        'pdf_only': 'لطفاً فقط فایل PDF انتخاب کنید',
        'play_tutorial': 'پخش فیلم آموزشی',
        'please_wait': 'لطفاً صبر کنید...',
        'preparing_widgets': 'در حال آماده‌سازی ویجت‌ها...',
        'preview_cover': 'پیش‌نمایش جلد',
        'preview_error': 'خطا در ایجاد پیش‌نمایش',
        'preview_tooltip': 'مشاهده پیش‌نمایش جلد قبل از ساخت',
        'progress_back_page': 'در حال انتخاب صفحه پشت جلد...',
        'progress_complete': 'ساخت جلد با موفقیت به پایان رسید!',
        'progress_creating_cover': 'در حال ساخت جلد نهایی...',
        'progress_error': 'خطا در ساخت جلد!',
        'progress_front_page': 'در حال انتخاب صفحه روی جلد...',
        'progress_init': 'آماده‌سازی اولیه...',
        'progress_pdf_load': 'در حال بارگذاری فایل PDF...',
        'progress_processing': 'در حال پردازش تصاویر...',
        'progress_saving': 'در حال ذخیره فایل...',
        'progress_text_processing': 'در حال پردازش متن‌ها...',

        # R
        'rate_experience': 'به تجربه خود از برنامه امتیاز دهید',
        'refresh': 'به روزرسانی',
        'refresh_page': 'پاکسازی صفحه',
        'refresh_tooltip': 'پاکسازی فرم و reset کردن همه فیلدها',
        'register': 'ثبت نام',
        'register_success': 'ثبت نام با موفقیت انجام شد',
        'register_title': 'ثبت نام کاربر جدید',
        'remaining': 'زمان باقی‌مانده',
        'remember_me': 'مرا به خاطر بسپار',
        'reset_view': 'بازنشانی دید',
        'restart_error': 'خطا در راه اندازی مجدد',
        'restart_question': 'برای اعمال تغییرات، برنامه باید مجدداً راه اندازی شود. آیا می خواهید اکنون راه اندازی مجدد شود؟',
        'restarting': 'در حال راه اندازی مجدد...',
        'result': 'نتیجه از',
        'rotation': 'چرخش',

        # S
        'save_file': 'ذخیره فایل',
        'save_location': 'محل ذخیره',
        'save_location_tooltip': 'انتخاب مسیر ذخیره فایل نهایی',
        'search_all': 'همه',
        'search_in_author': 'نویسنده',
        'search_in_date': 'تاریخ',
        'search_in_filename': 'نام فایل',
        'search_in_title': 'عنوان',
        'search_placeholder': 'جستجو در عنوان، نویسنده، تاریخ...',
        'select_color': 'انتخاب رنگ',
        'select_date': 'انتخاب تاریخ',
        'select_file': 'انتخاب فایل',
        'select_file_tooltip': 'انتخاب فایل PDF پایان‌نامه',
        'select_folder': 'انتخاب پوشه',
        'select_month': 'انتخاب ماه',
        'select_pdf_first': 'لطفاً ابتدا فایل PDF را انتخاب کنید',
        'select_rating': 'لطفاً امتیاز دهید',
        'select_rating_warning': 'لطفاً ابتدا امتیاز دهید',
        'select_year': 'انتخاب سال',
        'selected_date': 'تاریخ انتخاب شده',
        'selected_page': 'صفحه انتخاب شده',
        'session_expired': 'جلسه منقضی شد',
        'session_expired_message': 'جلسه شما منقضی شده است. لطفاً مجدداً وارد شوید.',
        'shortcut_back_to_main': 'بازگشت به صفحه اصلی',
        'shortcut_calc_spine': 'محاسبه خودکار عطف',
        'shortcut_check_update': 'بررسی به روزرسانی',
        'shortcut_delete_item': 'حذف آیتم انتخاب شده',
        'shortcut_new_project': 'پروژه جدید (پاک کردن فرم)',
        'shortcut_open_pdf': 'انتخاب فایل PDF',
        'shortcut_quick_help': 'راهنمای سریع میانبرها',
        'shortcut_refresh_form': 'پاکسازی فرم',
        'shortcut_save_location': 'انتخاب محل ذخیره',
        'shortcut_select_all': 'انتخاب همه آیتم‌ها',
        'shortcut_show_calendar': 'انتخاب تاریخ (تقویم)',
        'shortcut_show_help': 'نمایش راهنمای کامل',
        'shortcut_show_history': 'نمایش تاریخچه',
        'shortcut_show_theme': 'نمایش تم‌ها',
        'shortcut_start_making': 'شروع ساخت جلد',
        'shortcuts': 'میانبرها',
        'shortcuts_note': 'برای استفاده از میانبرها، کلیدهای ترکیبی را همزمان فشار دهید',
        'size_author': 'اندازه نام نویسنده',
        'size_title': 'اندازه عنوان',
        'skip': 'رد کردن',
        'spine': 'عطف',
        'spine_calculation': 'محاسبه عطف',
        'spine_calc_tooltip': 'محاسبه خودکار عطف از روی فایل PDF',
        'spine_formula': 'فرمول محاسبه عطف: SP = [n × (P/100)] / 20 + 5\nn: تعداد صفحات کتاب\nP: وزن هر ورق کاغذ (گرم)\nنکته: 5 میلی‌متر بابت مقوای جلد اضافه می‌شود',
        'spine_number_error': 'مقدار عطف باید عدد باشد',
        'spine_placeholder': 'مقدار عطف',
        'spine_tooltip': 'مقدار عطف را به میلی‌متر وارد کنید',
        'spine_value': 'عطف',
        'start_making': 'شروع ساخت',
        'start_tooltip': 'شروع ساخت جلد پایان‌نامه',
        'start_update': 'شروع به روزرسانی',
        'starting_app': 'در حال راه‌اندازی برنامه...',
        'stars': 'ستاره ها',
        'stats': 'آمار',
        'status': 'وضعیت:',
        'step1': 'مرحله ۱',
        'step2': 'مرحله ۲',
        'step3': 'مرحله ۳',
        'submit_feedback': 'ارسال نظر',
        'success': 'موفقیت',
        'suggestions': 'پیشنهادات',
        'suggestions_placeholder': 'پیشنهادات خود را برای بهبود برنامه بنویسید...',

        # T
        'thanks': 'ممنون',
        'theme_button': 'تم ها',
        'theme_guide_message': 'یکی از رنگ ها را انتخاب کنید تا رنگ تمام دکمه های برنامه عوض شود',
        'theme_guide_title': 'راهنمای تنظیم تم برنامه',
        'theme_tooltip': 'تغییر تم و رنگ‌های برنامه',
        'this_month': 'این ماه',
        'this_week': 'این هفته',
        'this_year': 'امسال',
        'title': 'عنوان',
        'title_back': 'عنوان پشت جلد',
        'title_font': 'فونت عنوان',
        'title_on': 'عنوان روی جلد',
        'title_placeholder': 'عنوان',
        'title_tooltip': 'عنوان پایان‌نامه را وارد کنید',
        'today': 'امروز',
        'tutorial_description': 'این فیلم آموزشی نحوه استفاده از برنامه ساخت جلد را به شما نشان می‌دهد.',
        'tutorial_video': 'فیلم آموزشی',

        # U
        'unknown': 'نامشخص',
        'update': 'به روزرسانی',
        'update_error': 'خطا در به روزرسانی',
        'update_note': 'توجه: فایل های .gitignore و README.md به روزرسانی نمی شوند.',
        'update_question': 'آیا می خواهید به روزرسانی کنید؟',
        'update_successful': 'به روزرسانی با موفقیت انجام شد (نسخه {})',
        'update_successful_message': 'برنامه با موفقیت به نسخه',
        'update_successful_title': 'به روزرسانی موفق',
        'update_title': 'بررسی به روزرسانی',
        'update_tooltip': 'بررسی بروزرسانی جدید',
        'updated_at': 'آخرین به روزرسانی',
        'updating': 'در حال به روزرسانی...',
        'username': 'نام کاربری',
        'username_min_length': 'نام کاربری حداقل ۳ کاراکتر باید باشد',
        'username_placeholder': 'نام کاربری خود را وارد کنید',

        # V
        'very_bad': 'خیلی ضعیف',
        'video_not_found': 'فیلم آموزشی یافت نشد',
        'video_placeholder': 'ویدئو در اینجا نمایش داده می‌شود',
        'view_on_github': 'مشاهده در گیت‌هاب',

        # W
        'warning': 'هشدار',
        'watch_tutorial': 'پخش فیلم آموزشی',
        'welcome_back': 'خوش آمدید',
        'welcome_message': 'به برنامه ساخت جلد خوش آمدید',
        'Weekdays': ['شنبه', 'یکشنبه', 'دوشنبه', 'سه‌شنبه', 'چهارشنبه', 'پنجشنبه', 'جمعه'],

        # Y
        'yes': 'بله',

        # ===== Page Selector Keys =====
        'page_selector_title_front': 'انتخاب صفحه روی جلد (۱۰ صفحه اول)',
        'page_selector_title_back': 'انتخاب صفحه پشت جلد (۱۰ صفحه آخر)',
        'page_selector_no_back_cover': '📄 بدون صفحه پشت جلد',
        'page_selector_loading': '⏳ در حال بارگذاری صفحات...',
        'page_selector_no_page_selected': '📄 صفحه‌ای انتخاب نشده است',
        'page_selector_page': 'صفحه',
        'page_selector_page_selected': '✅ صفحه انتخاب شده: {}',
        'page_selector_select_page': 'لطفاً یک صفحه را انتخاب کنید',
        'page_selector_no_pages': '❌ هیچ صفحه‌ای برای نمایش وجود ندارد',
        'page_selector_no_back_cover_ok': '✅ بدون صفحه پشت جلد',
        'page_selector_pdf_not_found': 'فایل PDF یافت نشد',
        'page_selector_pdf_empty': 'فایل PDF خالی است',
        'page_selector_pdf_error': 'خطا در بارگذاری PDF: {}',
        'page_selector_timeout': 'زمان بارگذاری به پایان رسید',
        'page_selector_placeholder': 'صفحه {}',
    },

    'english': {
        # A
        'about_button': 'About',
        'about_message': '''
                        App Name: Cover Builder
                        Developers: MUSHAK Team
                        Version: {}
                        Grade: 8
                        School: Meshkini Brilliant Talents
                        Contact: 09300828112 - 09941100534

                        We have developed the Cover Maker program
                        with the aim of facilitating the process of
                        designing creative and professional covers

                        This program is specially designed for students and bookbinders
                        so that they can easily create unique covers
                        We at the MUSHAK Development Group will provide you with a perfect
                        experience by focusing on completing and activating all the features

                        Kharazmi Competitions 1404-1405
                        Support: example@example.com
                        ''',
        'about_title': 'About App',
        'about_tooltip': 'About the program and developers',
        'ai_extract': 'AI Extract',
        'ai_extract_failed': 'Failed to extract information',
        'ai_extract_success': 'Information extracted successfully',
        'ai_extract_tooltip': 'Auto extract title, author and date from PDF using AI',
        'app_title': 'Cover Builder',
        'app_up_to_date': 'App is up to date',
        'apply': 'Apply',
        'author': 'Author',
        'author_font': 'Author Font',
        'author_name': 'Author Name',
        'author_placeholder': 'Author Name',
        'author_tooltip': 'Enter the author name of the dissertation',
        'auto_rotate': 'Auto Rotate',
        'average': 'Average',
        'average_all': 'Average volume per day:',

        # B
        'back': 'Back',
        'back_tooltip': 'Return to previous page',
        'background_color': 'Background Color',
        'background_tooltip': 'Select the background color of the app',
        'bad': 'Bad',
        'book_cover': 'Book Cover',
        'book_dimensions': 'Dimensions',
        'book_settings': 'Book Settings',
        'book_title': 'Title',
        'both_sides_printed': 'Double-sided printed thesis',
        'both_sides_tooltip': 'Check if the thesis is printed on both sides',

        # C
        'calendar_icon': '📅',
        'calendar_tooltip': 'Select date from calendar',
        'cancel': 'Cancel',
        'cancel_create': 'Cancel creation?',
        'changed': 'Changed',
        'check_again': 'Check Again',
        'check_update': 'Check Update',
        'checking': 'Checking...',
        'checking_updates': 'Checking for updates...',
        'choose_back_page': 'Select the back cover page',
        'choose_front_page': 'Select the front cover page',
        'clear_all': 'Clear All',
        'clear_all_confirm': 'Clear all history?',
        'clear_all_success': 'All history cleared successfully',
        'clear_all_tooltip': 'Clear all history',
        'clear_remember_question': 'Clear Remember Me data too?',
        'clear_search': 'Clear search',
        'close': 'Close',
        'close_tooltip': 'Close the application',
        'comment': 'Comment',
        'comment_placeholder': 'Write your feedback...',
        'confirm_password': 'Confirm Password',
        'confirm_password_placeholder': 'Re-enter password',
        'connecting_github': 'Connecting to GitHub...',
        'construction_info': 'Construction Info',
        'copyed': 'Copied',
        'cover': 'Cover',
        'cover_created': 'Cover created',
        'cover_created_success': 'Cover created successfully',
        'created_at': 'Created at',
        'creation_date': 'Creation Date',
        'current_version': 'Current version',
        'current_version_checking': 'Current version: Checking...',
        'current_version_unknown': 'Current version: Unknown',

        # D
        'date': 'Date',
        'date_placeholder': 'Date',
        'date_tooltip': 'Enter the thesis date',
        'delete': 'Delete',
        'delete_confirm': 'Delete {}?',
        'description': 'Description',
        'developer_team': 'MUSHAK Team',
        'dissertation_cover': 'Dissertation Cover',
        'dissertation_number': 'How many pages does the thesis have?',
        'dissertation_tooltip': 'Create dissertation cover',
        'download': 'Download',
        'download_error': 'Download Error',
        'downloading_updating': 'Downloading and updating...',
        'drag_drop_hint': 'Drag and drop PDF file here',

        # E
        'edit': 'Edit',
        'email': 'Email',
        'email_placeholder': 'Enter your email',
        'empty_credentials': 'Please enter username and password',
        'empty_fields_error': 'Empty fields:\n{}',
        'empty_history': 'History is empty',
        'enter_page_count': 'Enter page count',
        'enter_spine_first': 'Please enter spine value first',
        'enter_title_first': 'Please enter title first',
        'enter_valid_number': 'Please enter a valid number',
        'err': 'Enter numbers for spine',
        'error': 'Error',
        'error_during_update': 'Error during update:',
        'error_extract': 'Error extracting files. Could not find the main repository directory.',
        'error_network_during_update': 'Network error during update:',
        'error_restarting_program': 'Error restarting program:',
        'error_starting': 'Error starting:',
        'excellent': 'Excellent',
        'exit': 'Exit',
        'extracting': 'Extracting...',

        # F
        'feedback_error': 'Error submitting feedback',
        'feedback_thanks': 'Thank you for your feedback!',
        'feedback_title': 'Your Feedback',
        'file_and_size': 'File and Size',
        'file_name': 'File Name',
        'file_saved_to': 'File saved to',
        'file_section': 'Files',
        'file_selected': 'File selected',
        'filter_date_range': 'Date Range Filter',
        'folder_selected': 'Folder selected',
        'font': 'Font',
        'font_sample': 'Sample Text',
        'form_cleared': 'Form cleared successfully',
        'full_name': 'Full Name',
        'full_name_placeholder': 'Full name',

        # G
        'general': 'General',
        'github_connection_error': 'GitHub connection error',
        'github_error': 'GitHub error',
        'gilded_book_cover': 'Gilded Cover',
        'good': 'Good',
        'guest': 'Guest',
        'guest_login': 'Login as Guest',
        'guest_login_error': 'Guest login error',
        'guest_welcome': 'Welcome as guest',
        'guide': 'Guide',
        'guide_button': 'Help',
        'guide_result': 'Final Result:\n• Cover is displayed\n• File saved in selected path',
        'guide_step1_desc': 'Enter the title (for spine), author name, date, and spine width.',
        'guide_step1_title': 'Step 1: Basic Information',
        'guide_step2_desc': 'Choose your dissertation PDF file and specify where to save the final file.',
        'guide_step2_title': 'Step 2: Select File & Save Location',
        'guide_step3_desc': 'Click "Start Making", then select the front and back cover pages.',
        'guide_step3_title': 'Step 3: Create & Save Cover',
        'guide_tooltip': 'Application usage guide',

        # H
        'has_latin_page_off': 'No Latin page',
        'has_latin_page_on': 'Has Latin page',
        'has_latin_page_text': 'Dissertation has Latin page',
        'hello': 'Hello',
        'history_all_time': 'All time',
        'history_button': 'History',
        'history_last_3_months': 'Last 3 Months',
        'history_last_6_months': 'Last 6 Months',
        'history_last_year': 'Last Year',
        'history_stats': 'History Statistics',
        'history_this_month': 'This Month',
        'history_this_week': 'This Week',
        'history_this_year': 'This Year',
        'history_today': 'Today',
        'history_tooltip': 'View cover creation history',

        # I
        'id': 'ID: {} \n {}',
        'inactive': 'Inactive',
        'inactive_frame': 'Coming soon in future updates',
        'info_title': 'Dissertation Info',

        # K
        'Kharazmi': 'Kharazmi',
        'keyboard_shortcuts': 'Keyboard Shortcuts',

        # L
        'language': 'Language',
        'language_tooltip': 'Change application language',
        'latest_version': 'Latest version',
        'latest_version_checking': 'Latest version: Checking...',
        'level': 'Level',
        'level_tooltip': 'Select thesis level (for seminary theses)',
        'link': 'Link',
        'loading': 'Loading...',
        'loading_database': 'Connecting to database...',
        'loading_fonts': 'Loading fonts...',
        'loading_modules': 'Loading modules...',
        'loading_repos': 'Loading...',
        'loading_theme': 'Setting up theme...',
        'login': 'Login',
        'logout': 'Logout',
        'logout_confirm': 'Are you sure you want to logout?',
        'logo_n_found': 'Logo not found',

        # M
        'main_menu': 'Main Menu',
        'main_script_not_found': 'Main script \'main.py\' not found. Cannot restart program.',
        'media_access_denied': 'Access denied',
        'media_format_error': 'Format not supported',
        'media_network_error': 'Network error',
        'media_resource_error': 'Error loading file',
        'media_service_missing': 'Media service unavailable',
        'media_unknown_error': 'Unknown media error',
        'minimize': 'Minimize window',
        'months': ['Farvardin', 'Ordibehesht', 'Khordad', 'Tir', 'Mordad', 'Shahrivar', 'Mehr', 'Aban', 'Azar', 'Dey', 'Bahman', 'Esfand'],
        'more_info': 'More Info',

        # N
        'new_version_available': 'New version {} available',
        'new_version_found': 'New version',
        'no': 'No',
        'no_account': "Don't have an account?",
        'no_back_cover': 'No Back Cover',
        'no_back_cover_tooltip': 'Check if the thesis has no back cover',
        'no_description': 'No description',
        'no_file_selected': 'No file selected',
        'no_folder_selected': 'No folder selected',
        'no_level': 'No Level',
        'no_logo_selected': 'No logo selected',
        'no_other_programs': 'No other programs found',
        'no_page_selected': 'No page selected',
        'no_results': 'No results found',
        'notebook_cover': 'Notebook Cover',
        'number_all': 'Total number of volumes made:',

        # O
        'open_file': 'Open File',
        'open_location': 'Open Location',
        'original_path': 'Original Path',
        'other_colors': 'Other Colors',
        'other_colors_tooltip': 'Select custom color for buttons from Color Picker',
        'other_programs': 'Other Programs',
        'other_programs_title': 'Our other programs',
        'other_tooltip': 'View other programs',
        'output_file_name': 'Output name',

        # P
        'page_number': 'Page',
        'pages_doubled': 'pages will be doubled',
        'password': 'Password',
        'password_min_length': 'Password must be at least 4 characters',
        'password_mismatch': 'Passwords do not match',
        'password_placeholder': 'Enter your password',
        'pause_rotation': 'Pause Rotation',
        'pdf_file': 'PDF file',
        'pdf_file_cannot_be_opened': 'PDF file cannot be opened:',
        'pdf_only': 'Please select only PDF file',
        'play_tutorial': 'Play Tutorial',
        'please_wait': 'Please wait...',
        'preparing_widgets': 'Preparing widgets...',
        'preview_cover': 'Preview Cover',
        'preview_error': 'Error creating preview',
        'preview_tooltip': 'Preview cover before creating',
        'progress_back_page': 'Selecting back cover page...',
        'progress_complete': 'Cover created successfully!',
        'progress_creating_cover': 'Creating final cover...',
        'progress_error': 'Error creating cover!',
        'progress_front_page': 'Selecting front cover page...',
        'progress_init': 'Initializing...',
        'progress_pdf_load': 'Loading PDF file...',
        'progress_processing': 'Processing images...',
        'progress_saving': 'Saving file...',
        'progress_text_processing': 'Processing texts...',

        # R
        'rate_experience': 'Rate your experience',
        'refresh': 'Refresh',
        'refresh_page': 'Clear Form',
        'refresh_tooltip': 'Clear form and reset all fields',
        'register': 'Register',
        'register_success': 'Registration successful',
        'register_title': 'Register New User',
        'remaining': 'Remaining time',
        'remember_me': 'Remember Me',
        'reset_view': 'Reset View',
        'restart_error': 'Restart error',
        'restart_question': 'Restart now?',
        'restarting': 'Restarting...',
        'result': 'The result of',
        'rotation': 'Rotation',

        # S
        'save_file': 'Save File',
        'save_location': 'Save Location',
        'save_location_tooltip': 'Select the save location for the final file',
        'search_all': 'All',
        'search_in_author': 'Author',
        'search_in_date': 'Date',
        'search_in_filename': 'Filename',
        'search_in_title': 'Title',
        'search_placeholder': 'Search in title, author, date...',
        'select_color': 'Select Color',
        'select_date': 'Select Date',
        'select_file': 'Select File',
        'select_file_tooltip': 'Select the dissertation PDF file',
        'select_folder': 'Select Folder',
        'select_month': 'Select Month',
        'select_pdf_first': 'Please select PDF file first',
        'select_rating': 'Please rate',
        'select_rating_warning': 'Please select a rating first',
        'select_year': 'Select Year',
        'selected_date': 'Selected Date',
        'selected_page': 'Selected page',
        'session_expired': 'Session Expired',
        'session_expired_message': 'Your session has expired. Please login again.',
        'shortcut_back_to_main': 'Back to Main Page',
        'shortcut_calc_spine': 'Auto Calculate Spine',
        'shortcut_check_update': 'Check for Updates',
        'shortcut_delete_item': 'Delete Selected Item',
        'shortcut_new_project': 'New Project (Clear Form)',
        'shortcut_open_pdf': 'Open PDF File',
        'shortcut_quick_help': 'Quick Shortcuts Help',
        'shortcut_refresh_form': 'Clear Form',
        'shortcut_save_location': 'Select Save Location',
        'shortcut_select_all': 'Select All Items',
        'shortcut_show_calendar': 'Select Date (Calendar)',
        'shortcut_show_help': 'Show Full Help',
        'shortcut_show_history': 'Show History',
        'shortcut_show_theme': 'Show Themes',
        'shortcut_start_making': 'Start Making Cover',
        'shortcuts': 'Shortcuts',
        'shortcuts_note': 'Press shortcut keys simultaneously',
        'size_author': 'Author size',
        'size_title': 'Title size',
        'skip': 'Skip',
        'spine': 'Spine',
        'spine_calculation': 'Spine calculation',
        'spine_calc_tooltip': 'Auto calculate spine from PDF file',
        'spine_formula': 'Spine formula: SP = [n × (P/100)] / 20 + 5\nn: Number of pages\nP: Paper weight (grams)\nNote: 5mm added for cover board',
        'spine_number_error': 'Spine must be number',
        'spine_placeholder': 'Spine Value',
        'spine_tooltip': 'Enter spine width in millimeters',
        'spine_value': 'Spine',
        'start_making': 'Start Making',
        'start_tooltip': 'Start creating the dissertation cover',
        'start_update': 'Start Update',
        'starting_app': 'Starting application...',
        'stars': 'Stars',
        'stats': 'Stats',
        'status': 'Status:',
        'step1': 'Step 1',
        'step2': 'Step 2',
        'step3': 'Step 3',
        'submit_feedback': 'Submit Feedback',
        'success': 'Success',
        'suggestions': 'Suggestions',
        'suggestions_placeholder': 'Suggestions for improvement...',

        # T
        'thanks': 'Thanks',
        'theme_button': 'Theme',
        'theme_guide_message': 'Select a color to change all button colors',
        'theme_guide_title': 'Theme Configuration Guide',
        'theme_tooltip': 'Change theme and colors',
        'this_month': 'This Month',
        'this_week': 'This Week',
        'this_year': 'This Year',
        'title': 'Title',
        'title_back': 'Back Title',
        'title_font': 'Title Font',
        'title_on': 'Front Title',
        'title_placeholder': 'Title',
        'title_tooltip': 'Enter the dissertation title',
        'today': 'Today',
        'tutorial_description': 'This tutorial video shows you how to use the Cover Builder application.',
        'tutorial_video': 'Tutorial Video',

        # U
        'unknown': 'Unknown',
        'update': 'Update',
        'update_error': 'Update error',
        'update_note': 'Note: .gitignore and README.md not updated',
        'update_question': 'Update now?',
        'update_successful': 'Update successful (version {})',
        'update_successful_message': 'Successfully updated to version',
        'update_successful_title': 'Update Success',
        'update_title': 'Check Updates',
        'update_tooltip': 'Check for new updates',
        'updated_at': 'Updated at',
        'updating': 'Updating...',
        'username': 'Username',
        'username_min_length': 'Username must be at least 3 characters',
        'username_placeholder': 'Enter your username',

        # V
        'very_bad': 'Very Bad',
        'video_not_found': 'Tutorial video not found',
        'video_placeholder': 'Video will be displayed here',
        'view_on_github': 'View on GitHub',

        # W
        'warning': 'Warning',
        'watch_tutorial': 'Watch Tutorial',
        'welcome_back': 'Welcome back',
        'welcome_message': 'Welcome to Cover Builder',
        'Weekdays': ['Saturday', 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
        # Y
        'yes': 'Yes',

        # ===== Page Selector Keys =====
        'page_selector_title_front': 'Select Front Cover Page (First 10 Pages)',
        'page_selector_title_back': 'Select Back Cover Page (Last 10 Pages)',
        'page_selector_no_back_cover': '📄 No Back Cover',
        'page_selector_loading': '⏳ Loading pages...',
        'page_selector_no_page_selected': '📄 No page selected',
        'page_selector_page': 'Page',
        'page_selector_page_selected': '✅ Selected page: {}',
        'page_selector_select_page': 'Please select a page',
        'page_selector_no_pages': '❌ No pages to display',
        'page_selector_no_back_cover_ok': '✅ No Back Cover',
        'page_selector_pdf_not_found': 'PDF file not found',
        'page_selector_pdf_empty': 'PDF file is empty',
        'page_selector_pdf_error': 'Error loading PDF: {}',
        'page_selector_timeout': 'Loading timeout',
        'page_selector_placeholder': 'Page {}',
    },

    'arabic': {
        # A
        'about_button': 'معلومات عنا',
        'about_message': '''
                        اسم البرنامج: صانع الأغلفة
                        المطورون: فريق موشك
                        الإصدار: {}
                        الصف: 8
                        المدرسة: مدرسة مشكيني للمواهب اللامعة
                        للتواصل: 09300828112 - 09941100534

                        لقد طورنا برنامج صانع الأغلفة
                        بهدف تسهيل عملية تصميم أغلفة إبداعية واحترافية
                        هذا البرنامج مصمم خصيصًا للطلاب ومجلّدي الكتب،
                        ليتمكنوا من إنشاء أغلفة فريدة بسهولة
                        نحن في مجموعة موشك للتطوير نضمن لكم تجربة مثالية
                        من خلال التركيز على إكمال وتفعيل جميع الميزات

                        مهرجان خوارزمي 1404-1405
                        الدعم: example@example.com
                        ''',
        'about_title': 'حول البرنامج',
        'about_tooltip': 'حول البرنامج والمطورين',
        'ai_extract': 'استخراج بالذكاء الاصطناعي',
        'ai_extract_failed': 'فشل في استخراج المعلومات',
        'ai_extract_success': 'تم استخراج المعلومات بنجاح',
        'ai_extract_tooltip': 'استخراج تلقائي للعنوان والمؤلف والتاريخ من ملف PDF باستخدام الذكاء الاصطناعي',
        'app_title': 'صانع الأغلفة',
        'app_up_to_date': 'البرنامج محدث',
        'apply': 'تطبيق',
        'author': 'المؤلف',
        'author_font': 'خط المؤلف',
        'author_name': 'اسم المؤلف',
        'author_placeholder': 'اسم المؤلف',
        'author_tooltip': 'أدخل اسم مؤلف الرسالة',
        'auto_rotate': 'تدوير تلقائي',
        'average': 'متوسط',
        'average_all': 'متوسط الحجم اليومي:',

        # B
        'back': 'رجوع',
        'back_tooltip': 'العودة إلى الصفحة السابقة',
        'background_color': 'لون الخلفية',
        'background_tooltip': 'اختر لون خلفية البرنامج',
        'bad': 'ضعيف',
        'book_cover': 'غلاف الكتاب',
        'book_dimensions': 'الأبعاد',
        'book_settings': 'إعدادات الكتاب',
        'book_title': 'العنوان',
        'both_sides_printed': 'الأطروحة مطبوعة على الوجهين',
        'both_sides_tooltip': 'حدد إذا كانت الأطروحة مطبوعة على الوجهين',

        # C
        'calendar_icon': '📅',
        'calendar_tooltip': 'اختر التاريخ من التقويم',
        'cancel': 'إلغاء',
        'cancel_create': 'إلغاء الإنشاء؟',
        'changed': 'تم التغيير',
        'check_again': 'تحقق مرة أخرى',
        'check_update': 'التحقق من التحديث',
        'checking': 'جاري التحقق...',
        'checking_updates': 'جاري التحقق من التحديثات...',
        'choose_back_page': 'اختر صفحة الغلاف الخلفي',
        'choose_front_page': 'اختر صفحة الغلاف الأمامي',
        'clear_all': 'مسح الكل',
        'clear_all_confirm': 'مسح التاريخ بالكامل؟',
        'clear_all_success': 'تم مسح التاريخ بالكامل بنجاح',
        'clear_all_tooltip': 'مسح كل التاريخ',
        'clear_remember_question': 'هل تريد مسح بيانات تذكرني أيضاً؟',
        'clear_search': 'مسح البحث',
        'close': 'إغلاق',
        'close_tooltip': 'إغلاق البرنامج',
        'comment': 'تعليق',
        'comment_placeholder': 'اكتب رأيك في البرنامج...',
        'confirm_password': 'تأكيد كلمة المرور',
        'confirm_password_placeholder': 'أعد إدخال كلمة المرور',
        'connecting_github': 'الاتصال بـ GitHub...',
        'construction_info': 'معلومات الإنشاء',
        'copyed': 'تم النسخ',
        'cover': 'الغلاف',
        'cover_created': 'تم إنشاء الغلاف',
        'cover_created_success': 'تم إنشاء الغلاف بنجاح',
        'created_at': 'تاريخ الإنشاء',
        'creation_date': 'تاريخ الإنشاء',
        'current_version': 'الإصدار الحالي',
        'current_version_checking': 'الإصدار الحالي: جاري التحقق...',
        'current_version_unknown': 'الإصدار الحالي: غير معروف',

        # D
        'date': 'التاريخ',
        'date_placeholder': 'التاريخ',
        'date_tooltip': 'أدخل تاريخ الأطروحة',
        'delete': 'حذف',
        'delete_confirm': 'حذف {}؟',
        'description': 'الوصف',
        'developer_team': 'فريق موشك',
        'dissertation_cover': 'غلاف الرسالة',
        'dissertation_number': 'كم عدد صفحات التخرج؟',
        'dissertation_tooltip': 'إنشاء غلاف الأطروحة',
        'download': 'تحميل',
        'download_error': 'خطأ في التحميل',
        'downloading_updating': 'جاري التحميل والتحديث...',
        'drag_drop_hint': 'اسحب وأفلت ملف PDF هنا',

        # E
        'edit': 'تعديل',
        'email': 'البريد الإلكتروني',
        'email_placeholder': 'أدخل بريدك الإلكتروني',
        'empty_credentials': 'الرجاء إدخال اسم المستخدم وكلمة المرور',
        'empty_fields_error': 'الحقول الفارغة:\n{}',
        'empty_history': 'التاريخ فارغ',
        'enter_page_count': 'أدخل عدد الصفحات',
        'enter_spine_first': 'الرجاء إدخال قيمة العمود الفقري أولاً',
        'enter_title_first': 'الرجاء إدخال العنوان أولاً',
        'enter_valid_number': 'الرجاء إدخال رقم صحيح',
        'err': 'أدخل أرقاماً للعمود الفقري',
        'error': 'خطأ',
        'error_during_update': 'خطأ أثناء التحديث:',
        'error_extract': 'خطأ في استخراج الملفات. تعذر العثور على دليل المستودع الرئيسي.',
        'error_network_during_update': 'خطأ في الشبكة أثناء التحديث:',
        'error_restarting_program': 'خطأ في إعادة تشغيل البرنامج:',
        'error_starting': 'خطأ في البدء:',
        'excellent': 'ممتاز',
        'exit': 'خروج',
        'extracting': 'جاري الاستخراج...',

        # F
        'feedback_error': 'خطأ في إرسال الملاحظات',
        'feedback_thanks': 'شكراً لملاحظاتك!',
        'feedback_title': 'ملاحظاتك',
        'file_and_size': 'الملف والأبعاد',
        'file_name': 'اسم الملف',
        'file_saved_to': 'تم حفظ الملف في',
        'file_section': 'الملفات',
        'file_selected': 'تم اختيار الملف',
        'filter_date_range': 'تصفية الفترة الزمنية',
        'folder_selected': 'تم اختيار المجلد',
        'font': 'الخط',
        'font_sample': 'نص تجريبي',
        'form_cleared': 'تم مسح النموذج بنجاح',
        'full_name': 'الاسم الكامل',
        'full_name_placeholder': 'الاسم واللقب',

        # G
        'general': 'عام',
        'github_connection_error': 'خطأ في الاتصال بـ GitHub',
        'github_error': 'خطأ في GitHub',
        'gilded_book_cover': 'الغلاف المذهب',
        'good': 'جيد',
        'guest': 'ضيف',
        'guest_login': 'الدخول كضيف',
        'guest_login_error': 'خطأ في الدخول كضيف',
        'guest_welcome': 'مرحباً بك كضيف',
        'guide': 'الدليل',
        'guide_button': 'المساعدة',
        'guide_result': 'النتيجة النهائية:\n• يتم عرض الغلاف\n• حفظ الملف في المسار المحدد',
        'guide_step1_desc': 'أدخل العنوان (للعمود الفقري)، اسم المؤلف، التاريخ، وعرض العمود الفقري.',
        'guide_step1_title': 'الخطوة 1: المعلومات الأساسية',
        'guide_step2_desc': 'اختر ملف PDF الخاص برسالتك وحدد أين تريد حفظ الملف النهائي.',
        'guide_step2_title': 'الخطوة 2: اختيار الملف ومكان الحفظ',
        'guide_step3_desc': 'انقر بدء الإنشاء، ثم اختر صفحتي الغلاف الأمامي والخلفي.',
        'guide_step3_title': 'الخطوة 3: إنشاء وحفظ الغلاف',
        'guide_tooltip': 'دليل استخدام البرنامج',

        # H
        'has_latin_page_off': 'بدون صفحة لاتينية',
        'has_latin_page_on': 'لديه صفحة لاتينية',
        'has_latin_page_text': 'الرسالة تحتوي على صفحة لاتينية',
        'hello': 'مرحباً',
        'history_all_time': 'كل الوقت',
        'history_button': 'التاريخ',
        'history_last_3_months': 'آخر 3 أشهر',
        'history_last_6_months': 'آخر 6 أشهر',
        'history_last_year': 'العام الماضي',
        'history_stats': 'إحصائيات التاريخ',
        'history_this_month': 'هذا الشهر',
        'history_this_week': 'هذا الأسبوع',
        'history_this_year': 'هذه السنة',
        'history_today': 'اليوم',
        'history_tooltip': 'عرض تاريخ إنشاء الأغلفة',

        # I
        'id': 'المعرف: {} \n {}',
        'inactive': 'غير نشط',
        'inactive_frame': 'قريباً في التحديثات القادمة',
        'info_title': 'معلومات الرسالة',

        # K
        'Kharazmi': 'خوارزمی',
        'keyboard_shortcuts': 'اختصارات لوحة المفاتيح',

        # L
        'language': 'اللغة',
        'language_tooltip': 'تغيير لغة البرنامج',
        'latest_version': 'آخر إصدار',
        'latest_version_checking': 'آخر إصدار: جاري التحقق...',
        'level': 'المستوى',
        'level_tooltip': 'حدد مستوى الأطروحة (للأطروحات الحوزوية)',
        'link': 'الرابط',
        'loading': 'جاري التحميل...',
        'loading_database': 'الاتصال بقاعدة البيانات...',
        'loading_fonts': 'تحميل الخطوط...',
        'loading_modules': 'تحميل الوحدات...',
        'loading_repos': 'جاري التحميل...',
        'loading_theme': 'إعداد السمة...',
        'login': 'دخول',
        'logout': 'تسجيل الخروج',
        'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
        'logo_n_found': 'الشعار غير موجود',

        # M
        'main_menu': 'القائمة الرئيسية',
        'main_script_not_found': 'النص البرمجي الرئيسي \'main.py\' غير موجود. لا يمكن إعادة تشغيل البرنامج.',
        'media_access_denied': 'الوصول مرفوض',
        'media_format_error': 'التنسيق غير مدعوم',
        'media_network_error': 'خطأ في الشبكة',
        'media_resource_error': 'خطأ في تحميل الملف',
        'media_service_missing': 'خدمة التشغيل غير متوفرة',
        'media_unknown_error': 'خطأ غير معروف في التشغيل',
        'minimize': 'تصغير النافذة',
        'months': ['فرواردين', 'أرديبهشت', 'خرداد', 'تير', 'مرداد', 'شهريور', 'مهر', 'آبان', 'آذر', 'دي', 'بهمن', 'إسفند'],
        'more_info': 'مزيد من المعلومات',

        # N
        'new_version_available': 'الإصدار {} متوفر',
        'new_version_found': 'إصدار جديد',
        'no': 'لا',
        'no_account': 'ليس لديك حساب؟',
        'no_back_cover': 'لا يوجد غلاف خلفي',
        'no_back_cover_tooltip': 'حدد إذا كانت الأطروحة لا تحتوي على غلاف خلفي',
        'no_description': 'لا يوجد وصف',
        'no_file_selected': 'لم يتم اختيار ملف',
        'no_folder_selected': 'لم يتم اختيار مجلد',
        'no_level': 'بدون مستوى',
        'no_logo_selected': 'لم يتم اختيار شعار',
        'no_other_programs': 'لا توجد برامج أخرى',
        'no_page_selected': 'لم يتم اختيار صفحة',
        'no_results': 'لم يتم العثور على نتائج',
        'notebook_cover': 'غلاف الدفتر',
        'number_all': 'إجمالي عدد المجلدات المنتجة:',

        # O
        'open_file': 'فتح الملف',
        'open_location': 'فتح الموقع',
        'original_path': 'المسار الأصلي',
        'other_colors': 'ألوان أخرى',
        'other_colors_tooltip': 'اختر لون مخصص للأزرار من منتقي الألوان',
        'other_programs': 'برامج أخرى',
        'other_programs_title': 'برامجنا الأخرى',
        'other_tooltip': 'عرض البرامج الأخرى',
        'output_file_name': 'اسم المخرج',

        # P
        'page_number': 'صفحة',
        'pages_doubled': 'ستتضاعف الصفحات',
        'password': 'كلمة المرور',
        'password_min_length': 'يجب أن تتكون كلمة المرور من 4 أحرف على الأقل',
        'password_mismatch': 'كلمة المرور غير متطابقة',
        'password_placeholder': 'أدخل كلمة المرور',
        'pause_rotation': 'إيقاف التدوير',
        'pdf_file': 'ملف PDF',
        'pdf_file_cannot_be_opened': 'لا يمكن فتح ملف PDF:',
        'pdf_only': 'يرجى اختيار ملف PDF فقط',
        'play_tutorial': 'تشغيل الفيديو التعليمي',
        'please_wait': 'رجاء الانتظار...',
        'preparing_widgets': 'تحضير الأدوات...',
        'preview_cover': 'معاينة الغلاف',
        'preview_error': 'خطأ في إنشاء المعاينة',
        'preview_tooltip': 'معاينة الغلاف قبل الإنشاء',
        'progress_back_page': 'جاري اختيار صفحة الغلاف الخلفي...',
        'progress_complete': 'تم إنشاء الغلاف بنجاح!',
        'progress_creating_cover': 'جاري إنشاء الغلاف النهائي...',
        'progress_error': 'خطأ في إنشاء الغلاف!',
        'progress_front_page': 'جاري اختيار صفحة الغلاف الأمامي...',
        'progress_init': 'جاري التهيئة...',
        'progress_pdf_load': 'جاري تحميل ملف PDF...',
        'progress_processing': 'جاري معالجة الصور...',
        'progress_saving': 'جاري حفظ الملف...',
        'progress_text_processing': 'جاري معالجة النصوص...',

        # R
        'rate_experience': 'قيم تجربتك مع البرنامج',
        'refresh': 'تحديث',
        'refresh_page': 'مسح الحقول',
        'refresh_tooltip': 'مسح النموذج وإعادة تعيين جميع الحقول',
        'register': 'تسجيل',
        'register_success': 'تم التسجيل بنجاح',
        'register_title': 'تسجيل مستخدم جديد',
        'remaining': 'الوقت المتبقي',
        'remember_me': 'تذكرني',
        'reset_view': 'إعادة تعيين العرض',
        'restart_error': 'خطأ في إعادة التشغيل',
        'restart_question': 'إعادة التشغيل الآن؟',
        'restarting': 'جاري إعادة التشغيل...',
        'result': 'نتيجة',
        'rotation': 'تدوير',

        # S
        'save_file': 'حفظ الملف',
        'save_location': 'مكان الحفظ',
        'save_location_tooltip': 'اختر موقع حفظ الملف النهائي',
        'search_all': 'الكل',
        'search_in_author': 'المؤلف',
        'search_in_date': 'التاريخ',
        'search_in_filename': 'اسم الملف',
        'search_in_title': 'العنوان',
        'search_placeholder': 'البحث في العنوان، المؤلف، التاريخ...',
        'select_color': 'اختر اللون',
        'select_date': 'اختر التاريخ',
        'select_file': 'اختر ملف',
        'select_file_tooltip': 'اختر ملف PDF الخاص بالأطروحة',
        'select_folder': 'اختر مجلد',
        'select_month': 'اختر الشهر',
        'select_pdf_first': 'الرجاء اختيار ملف PDF أولاً',
        'select_rating': 'الرجاء التقييم',
        'select_rating_warning': 'الرجاء اختيار التقييم أولاً',
        'select_year': 'اختر السنة',
        'selected_date': 'التاريخ المختار',
        'selected_page': 'الصفحة المختارة',
        'session_expired': 'انتهت الجلسة',
        'session_expired_message': 'انتهت جلستك. الرجاء تسجيل الدخول مرة أخرى.',
        'shortcut_back_to_main': 'العودة إلى الصفحة الرئيسية',
        'shortcut_calc_spine': 'حساب العمود الفقري تلقائياً',
        'shortcut_check_update': 'التحقق من التحديثات',
        'shortcut_delete_item': 'حذف العنصر المحدد',
        'shortcut_new_project': 'مشروع جديد (مسح النموذج)',
        'shortcut_open_pdf': 'فتح ملف PDF',
        'shortcut_quick_help': 'مساعدة سريعة للاختصارات',
        'shortcut_refresh_form': 'مسح النموذج',
        'shortcut_save_location': 'اختر موقع الحفظ',
        'shortcut_select_all': 'تحديد جميع العناصر',
        'shortcut_show_calendar': 'اختر التاريخ (التقويم)',
        'shortcut_show_help': 'عرض المساعدة الكاملة',
        'shortcut_show_history': 'عرض التاريخ',
        'shortcut_show_theme': 'عرض السمات',
        'shortcut_start_making': 'بدء بناء الغلاف',
        'shortcuts': 'الاختصارات',
        'shortcuts_note': 'اضغط على مفاتيح الاختصار في وقت واحد',
        'size_author': 'حجم المؤلف',
        'size_title': 'حجم العنوان',
        'skip': 'تخطي',
        'spine': 'العمود الفقري',
        'spine_calculation': 'حساب العطف',
        'spine_calc_tooltip': 'حساب العمود الفقري تلقائياً من ملف PDF',
        'spine_formula': 'معادلة العمود الفقري: SP = [n × (P/100)] / 20 + 5\nn: عدد الصفحات\nP: وزن الورقة (غرام)\nملاحظة: 5 مم إضافية للغلاف',
        'spine_number_error': 'القيمة يجب أن تكون رقم',
        'spine_placeholder': 'قيمة العمود الفقري',
        'spine_tooltip': 'أدخل عرض العمود الفقري بالميليمتر',
        'spine_value': 'العمود الفقري',
        'start_making': 'بدء الإنشاء',
        'start_tooltip': 'بدء إنشاء غلاف الأطروحة',
        'start_update': 'بدء التحديث',
        'starting_app': 'بدء التشغيل...',
        'stars': 'النجوم',
        'stats': 'إحصائيات',
        'status': 'الحالة:',
        'step1': 'الخطوة 1',
        'step2': 'الخطوة 2',
        'step3': 'الخطوة 3',
        'submit_feedback': 'إرسال الملاحظات',
        'success': 'نجاح',
        'suggestions': 'الاقتراحات',
        'suggestions_placeholder': 'اكتب اقتراحاتك لتحسين البرنامج...',

        # T
        'thanks': 'شكراً',
        'theme_button': 'السمات',
        'theme_guide_message': 'اختر لوناً لتغيير الأزرار',
        'theme_guide_title': 'دليل السمة',
        'theme_tooltip': 'تغيير السمة والألوان',
        'this_month': 'هذا الشهر',
        'this_week': 'هذا الأسبوع',
        'this_year': 'هذه السنة',
        'title': 'العنوان',
        'title_back': 'العنوان الخلفي',
        'title_font': 'خط العنوان',
        'title_on': 'العنوان الأمامي',
        'title_placeholder': 'العنوان',
        'title_tooltip': 'أدخل عنوان الأطروحة',
        'today': 'اليوم',
        'tutorial_description': 'يعرض هذا الفيديو التعليمي كيفية استخدام برنامج بناء الغلاف.',
        'tutorial_video': 'فيديو تعليمي',

        # U
        'unknown': 'غير معروف',
        'update': 'تحديث',
        'update_error': 'خطأ في التحديث',
        'update_note': 'ملاحظة: .gitignore و README.md لا يتم تحديثهما',
        'update_question': 'تحديث الآن؟',
        'update_successful': 'تم التحديث (الإصدار {})',
        'update_successful_message': 'تم التحديث إلى الإصدار',
        'update_successful_title': 'تحديث ناجح',
        'update_title': 'التحقق من التحديثات',
        'update_tooltip': 'التحقق من التحديثات الجديدة',
        'updated_at': 'آخر تحديث',
        'updating': 'جاري التحديث...',
        'username': 'اسم المستخدم',
        'username_min_length': 'اسم المستخدم يجب أن يكون 3 أحرف على الأقل',
        'username_placeholder': 'أدخل اسم المستخدم',

        # V
        'very_bad': 'سيء جداً',
        'video_not_found': 'الفيديو التعليمي غير موجود',
        'video_placeholder': 'سيتم عرض الفيديو هنا',
        'view_on_github': 'عرض في GitHub',

        # W
        'warning': 'تحذير',
        'watch_tutorial': 'مشاهدة الفيديو التعليمي',
        'welcome_back': 'مرحباً بعودتك',
        'welcome_message': 'مرحباً بكم في صانع الأغلفة',
        'Weekdays': ['السبت', 'الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة'],
        # Y
        'yes': 'نعم',

        # ===== Page Selector Keys =====
        'page_selector_title_front': 'اختيار صفحة الغلاف الأمامي (أول ١٠ صفحات)',
        'page_selector_title_back': 'اختيار صفحة الغلاف الخلفي (آخر ١٠ صفحات)',
        'page_selector_no_back_cover': '📄 لا يوجد غلاف خلفي',
        'page_selector_loading': '⏳ جاري تحميل الصفحات...',
        'page_selector_no_page_selected': '📄 لم يتم اختيار صفحة',
        'page_selector_page': 'صفحة',
        'page_selector_page_selected': '✅ الصفحة المختارة: {}',
        'page_selector_select_page': 'يرجى اختيار صفحة',
        'page_selector_no_pages': '❌ لا توجد صفحات للعرض',
        'page_selector_no_back_cover_ok': '✅ لا يوجد غلاف خلفي',
        'page_selector_pdf_not_found': 'ملف PDF غير موجود',
        'page_selector_pdf_empty': 'ملف PDF فارغ',
        'page_selector_pdf_error': 'خطأ في تحميل PDF: {}',
        'page_selector_timeout': 'انتهى وقت التحميل',
        'page_selector_placeholder': 'صفحة {}',
    }
}


# ========== توابع کمکی ==========

def get_text(key):
    """دریافت متن بر اساس کلید و زبان فعلی"""
    try:
        return languages[current_language][key]
    except KeyError:
        try:
            return languages['persian'][key]
        except KeyError:
            print(f"Key '{key}' not found in any language")
            return key


def set_language(lang):
    """تنظیم زبان برنامه"""
    global current_language
    if lang in languages:
        current_language = lang
        return True
    return False


def get_current_language():
    """دریافت زبان فعلی"""
    return current_language


def get_months():
    """دریافت لیست ماه‌ها به زبان فعلی"""
    return languages[current_language]['months']


def get_available_languages():
    """دریافت لیست زبان‌های موجود"""
    return list(languages.keys())


def get_date_range_options():
    """دریافت لیست گزینه‌های فیلتر بازه زمانی"""
    return [
        get_text('history_all_time'),
        get_text('history_today'),
        get_text('history_this_week'),
        get_text('history_this_month'),
        get_text('history_this_year'),
        get_text('history_last_3_months'),
        get_text('history_last_6_months'),
        get_text('history_last_year'),
    ]


def get_search_options():
    """دریافت لیست گزینه‌های جستجو"""
    return [
        get_text('search_all'),
        get_text('search_in_title'),
        get_text('search_in_author'),
        get_text('search_in_date'),
        get_text('search_in_filename')
    ]


def get_font(font_type='default'):
    """دریافت فونت B Titr با سایز مناسب"""
    fonts = {
        'default': QFont('B Titr', 14),
        'title': QFont('B Titr', 30),
        'button': QFont('B Titr', 15),
        'label': QFont('B Titr', 14),
        'entry': QFont('B Titr', 14),
        'small': QFont('B Titr', 12),
        'large': QFont('B Titr', 20),
        'huge': QFont('B Titr', 26),
    }
    return fonts.get(font_type, fonts['default'])


# متغیر زبان فعلی
current_language = 'persian'